//! Integration tests for `#[derive(PiiCodec)]`.
//!
//! These tests wire the generated [`PiiEventCodec`] implementation into a real
//! [`CryptoShreddingEventRepository`] backed by [`InMemoryEventRepository`] and
//! [`InMemoryKeyStore`] to verify that the derive macro produces correct code for
//! the full read/write cycle: encryption on persist, decryption on read, and
//! redaction when the DEK has been deleted (crypto-shredding).

use std::sync::Arc;

use cqrs_es::{
    DomainEvent,
    event_sink::EventSink,
    persist::{PersistedEventRepository, SerializedEvent},
};
use cqrs_es_crypto::{
    CryptoShreddingEventRepository, InMemoryEventRepository, InMemoryKeyStore, KeyStore, PiiCipher,
};
use cqrs_es_crypto_derive::PiiCodec;
use uuid::Uuid;

// ── Minimal aggregate (satisfies the type parameter) ─────────────────────────

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
enum TestDomainEvent {
    Noop,
}

impl DomainEvent for TestDomainEvent {
    fn event_type(&self) -> String {
        "Noop".to_string()
    }
    fn event_version(&self) -> String {
        "1.0".to_string()
    }
}

#[derive(Default, serde::Serialize, serde::Deserialize)]
struct TestAggregate;

impl cqrs_es::Aggregate for TestAggregate {
    type Command = ();
    type Event = TestDomainEvent;
    type Error = std::convert::Infallible;
    type Services = ();

    const TYPE: &'static str = "Test";

    async fn handle(
        &mut self,
        _command: (),
        _services: &(),
        _sink: &EventSink<Self>,
    ) -> Result<(), Self::Error> {
        Ok(())
    }

    fn apply(&mut self, _event: TestDomainEvent) {}
}

// ── Event enum under test ─────────────────────────────────────────────────────

/// A minimal event enum that exercises both the multi-secret and single-secret
/// code paths generated by `#[derive(PiiCodec)]`.
#[allow(dead_code)]
#[derive(PiiCodec)]
enum TestEvent {
    /// Multi-secret: several PII fields are bundled into a JSON object keyed
    /// by field name and encrypted as a single blob.
    #[pii(event_type = "MultiSecret")]
    MultiSecret {
        #[pii(plaintext)]
        tag: String,
        #[pii(subject)]
        subject_id: Uuid,
        #[pii(secret)]
        name: String,
        #[pii(secret)]
        email: String,
    },

    /// Single-secret: the one secret field is used as the blob directly
    /// (no wrapping object), with a custom sentinel field name.
    #[pii(event_type = "SingleSecret", sentinel = "encrypted_data")]
    SingleSecret {
        #[pii(plaintext)]
        tag: String,
        #[pii(subject)]
        subject_id: Uuid,
        #[pii(secret)]
        data: serde_json::Value,
    },

    /// Single-secret variant whose secret field is `chrono::NaiveDate`.
    /// Exercises the `chrono` feature's default redaction sentinel.
    #[cfg(feature = "chrono")]
    #[pii(event_type = "DatedSecret")]
    DatedSecret {
        #[pii(plaintext)]
        tag: String,
        #[pii(subject)]
        subject_id: Uuid,
        #[pii(secret)]
        dob: chrono::NaiveDate,
    },

    /// Single-secret variant whose secret field is `chrono::NaiveDate`
    /// with a custom redaction sentinel.
    #[cfg(feature = "chrono")]
    #[pii(event_type = "DatedSecretOverride")]
    DatedSecretOverride {
        #[pii(plaintext)]
        tag: String,
        #[pii(subject)]
        subject_id: Uuid,
        #[pii(secret, redact = "1900-01-01")]
        dob: chrono::NaiveDate,
    },

    /// Non-string plaintext fields. Exercises classify's preservation of the
    /// original JSON type for `#[pii(plaintext)]` fields whose Rust type is
    /// not `String` (e.g. integers, optional strings). A previous
    /// implementation coerced every plaintext field through
    /// `as_str().unwrap_or("")`, silently corrupting non-string fields to
    /// the empty string in the persisted payload and breaking deserialization
    /// on read-back.
    #[pii(event_type = "TypedPlaintext")]
    TypedPlaintext {
        #[pii(plaintext)]
        count: i32,
        #[pii(plaintext)]
        label: Option<String>,
        #[pii(subject)]
        subject_id: Uuid,
        #[pii(secret)]
        secret_value: String,
    },

    /// Non-PII variant — must pass through the repository completely unchanged.
    Plain,
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Build a test repository and return it together with the key store so that
/// individual tests can delete keys to exercise the redaction path.
fn make_repo_with_key_store() -> (
    CryptoShreddingEventRepository<InMemoryEventRepository>,
    Arc<InMemoryKeyStore>,
) {
    let key_store = Arc::new(InMemoryKeyStore::new());
    let cipher = PiiCipher::new(vec![0x42u8; 32]).unwrap();
    let codec = Arc::new(TestEventPiiCodec);
    let repo = CryptoShreddingEventRepository::new(
        InMemoryEventRepository::default(),
        Arc::clone(&key_store) as Arc<dyn KeyStore>,
        cipher,
        codec,
    );
    (repo, key_store)
}

fn make_repo() -> CryptoShreddingEventRepository<InMemoryEventRepository> {
    make_repo_with_key_store().0
}

fn multi_secret_event(aggregate_id: &str, sequence: usize, subject_id: Uuid) -> SerializedEvent {
    SerializedEvent::new(
        aggregate_id.to_string(),
        sequence,
        "Test".to_string(),
        "MultiSecret".to_string(),
        "1.0".to_string(),
        serde_json::json!({
            "MultiSecret": {
                "tag":        "some-tag",
                "subject_id": subject_id.to_string(),
                "name":       "Alice Smith",
                "email":      "alice@example.com",
            }
        }),
        serde_json::json!({}),
    )
}

fn single_secret_event(aggregate_id: &str, sequence: usize, subject_id: Uuid) -> SerializedEvent {
    SerializedEvent::new(
        aggregate_id.to_string(),
        sequence,
        "Test".to_string(),
        "SingleSecret".to_string(),
        "1.0".to_string(),
        serde_json::json!({
            "SingleSecret": {
                "tag":        "some-tag",
                "subject_id": subject_id.to_string(),
                "data":       { "passport": "GB123456" },
            }
        }),
        serde_json::json!({}),
    )
}

#[cfg(feature = "chrono")]
fn dated_secret_event(aggregate_id: &str, sequence: usize, subject_id: Uuid) -> SerializedEvent {
    SerializedEvent::new(
        aggregate_id.to_string(),
        sequence,
        "Test".to_string(),
        "DatedSecret".to_string(),
        "1.0".to_string(),
        serde_json::json!({
            "DatedSecret": {
                "tag":        "some-tag",
                "subject_id": subject_id.to_string(),
                "dob":        "1990-05-15",
            }
        }),
        serde_json::json!({}),
    )
}

#[cfg(feature = "chrono")]
fn dated_secret_override_event(
    aggregate_id: &str,
    sequence: usize,
    subject_id: Uuid,
) -> SerializedEvent {
    SerializedEvent::new(
        aggregate_id.to_string(),
        sequence,
        "Test".to_string(),
        "DatedSecretOverride".to_string(),
        "1.0".to_string(),
        serde_json::json!({
            "DatedSecretOverride": {
                "tag":        "some-tag",
                "subject_id": subject_id.to_string(),
                "dob":        "1990-05-15",
            }
        }),
        serde_json::json!({}),
    )
}

fn typed_plaintext_event(
    aggregate_id: &str,
    sequence: usize,
    subject_id: Uuid,
    count: i64,
    label: Option<&str>,
) -> SerializedEvent {
    SerializedEvent::new(
        aggregate_id.to_string(),
        sequence,
        "Test".to_string(),
        "TypedPlaintext".to_string(),
        "1.0".to_string(),
        serde_json::json!({
            "TypedPlaintext": {
                "count":        count,
                "label":        label,
                "subject_id":   subject_id.to_string(),
                "secret_value": "the-secret",
            }
        }),
        serde_json::json!({}),
    )
}

fn plain_event(aggregate_id: &str, sequence: usize) -> SerializedEvent {
    SerializedEvent::new(
        aggregate_id.to_string(),
        sequence,
        "Test".to_string(),
        "Plain".to_string(),
        "1.0".to_string(),
        serde_json::json!({ "Plain": {} }),
        serde_json::json!({}),
    )
}

// ── Write path: classify ──────────────────────────────────────────────────────

#[tokio::test]
async fn multi_secret_pii_fields_are_encrypted_on_persist() {
    let repo = make_repo();
    let aggregate_id = "ms-encrypt";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(&[multi_secret_event(aggregate_id, 1, subject_id)], None)
        .await
        .unwrap();

    let raw = repo.inner().all_events();
    assert_eq!(raw.len(), 1);
    let inner = &raw[0].payload["MultiSecret"];

    // PII fields must not appear in plaintext.
    assert!(inner.get("name").is_none(), "name must be encrypted");
    assert!(inner.get("email").is_none(), "email must be encrypted");

    // Default sentinel must be present.
    assert!(
        inner.get("encrypted_pii").is_some(),
        "encrypted_pii sentinel must be present"
    );
    assert!(inner.get("nonce").is_some(), "nonce must be present");

    // Non-PII fields are kept in plaintext.
    assert_eq!(inner["tag"].as_str().unwrap(), "some-tag");
    assert_eq!(
        inner["subject_id"].as_str().unwrap(),
        subject_id.to_string().as_str()
    );
}

#[tokio::test]
async fn single_secret_pii_field_is_encrypted_on_persist() {
    let repo = make_repo();
    let aggregate_id = "ss-encrypt";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(&[single_secret_event(aggregate_id, 1, subject_id)], None)
        .await
        .unwrap();

    let raw = repo.inner().all_events();
    let inner = &raw[0].payload["SingleSecret"];

    // PII field must not appear in plaintext.
    assert!(inner.get("data").is_none(), "data must be encrypted");

    // Custom sentinel must be present.
    assert!(
        inner.get("encrypted_data").is_some(),
        "encrypted_data sentinel must be present"
    );
    assert!(inner.get("nonce").is_some(), "nonce must be present");

    // Non-PII fields kept in plaintext.
    assert_eq!(inner["tag"].as_str().unwrap(), "some-tag");
    assert_eq!(
        inner["subject_id"].as_str().unwrap(),
        subject_id.to_string().as_str()
    );
}

#[tokio::test]
async fn non_pii_event_passes_through_unchanged() {
    let repo = make_repo();
    let aggregate_id = "plain-passthrough";
    let event = plain_event(aggregate_id, 1);
    let original_payload = event.payload.clone();

    repo.persist::<TestAggregate>(&[event], None).await.unwrap();

    let raw = repo.inner().all_events();
    assert_eq!(
        raw[0].payload, original_payload,
        "non-PII event must be stored verbatim"
    );
}

#[tokio::test]
async fn each_persist_produces_unique_ciphertext() {
    let repo = make_repo();
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(&[multi_secret_event("unique-1", 1, subject_id)], None)
        .await
        .unwrap();
    repo.persist::<TestAggregate>(&[multi_secret_event("unique-2", 1, subject_id)], None)
        .await
        .unwrap();

    let raw = repo.inner().all_events();
    let ct1 = raw[0].payload["MultiSecret"]["encrypted_pii"]
        .as_str()
        .unwrap();
    let ct2 = raw[1].payload["MultiSecret"]["encrypted_pii"]
        .as_str()
        .unwrap();

    assert_ne!(
        ct1, ct2,
        "a fresh nonce per encryption must produce distinct ciphertexts even for identical input"
    );
}

#[tokio::test]
async fn aad_binds_ciphertext_to_event_position() {
    // Persist two events for the same subject at different sequence numbers.
    // The AAD includes the aggregate_id and sequence, so even identical
    // plaintexts at different positions must produce different ciphertexts.
    let repo = make_repo();
    let aggregate_id = "aad-test";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(
        &[
            multi_secret_event(aggregate_id, 1, subject_id),
            multi_secret_event(aggregate_id, 2, subject_id),
        ],
        None,
    )
    .await
    .unwrap();

    let raw = repo.inner().all_events();
    let ct1 = raw[0].payload["MultiSecret"]["encrypted_pii"]
        .as_str()
        .unwrap();
    let ct2 = raw[1].payload["MultiSecret"]["encrypted_pii"]
        .as_str()
        .unwrap();

    assert_ne!(
        ct1, ct2,
        "different AAD (sequence number) must produce different ciphertexts"
    );
}

// ── Read path: full round-trip (reconstruct) ──────────────────────────────────

/// Persist a multi-secret event, then read it back and verify that all PII
/// fields are correctly decrypted and the non-PII fields are preserved.
#[tokio::test]
async fn multi_secret_round_trip_decrypts_pii_fields() {
    let repo = make_repo();
    let aggregate_id = "ms-roundtrip";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(&[multi_secret_event(aggregate_id, 1, subject_id)], None)
        .await
        .unwrap();

    let events = repo
        .get_events::<TestAggregate>(aggregate_id)
        .await
        .unwrap();

    assert_eq!(events.len(), 1);
    let inner = &events[0].payload["MultiSecret"];

    // PII fields must be decrypted.
    assert_eq!(
        inner["name"].as_str().unwrap(),
        "Alice Smith",
        "name must be decrypted"
    );
    assert_eq!(
        inner["email"].as_str().unwrap(),
        "alice@example.com",
        "email must be decrypted"
    );

    // Non-PII fields must be preserved.
    assert_eq!(inner["tag"].as_str().unwrap(), "some-tag");
    assert_eq!(
        inner["subject_id"].as_str().unwrap(),
        subject_id.to_string().as_str()
    );
}

/// Persist a single-secret event, then read it back and verify that the
/// secret `data` field is correctly reconstructed.
#[tokio::test]
async fn single_secret_round_trip_decrypts_pii_field() {
    let repo = make_repo();
    let aggregate_id = "ss-roundtrip";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(&[single_secret_event(aggregate_id, 1, subject_id)], None)
        .await
        .unwrap();

    let events = repo
        .get_events::<TestAggregate>(aggregate_id)
        .await
        .unwrap();

    assert_eq!(events.len(), 1);
    let inner = &events[0].payload["SingleSecret"];

    // The secret JSON value must be fully reconstructed.
    assert_eq!(
        inner["data"]["passport"].as_str().unwrap(),
        "GB123456",
        "data.passport must be decrypted"
    );

    // Non-PII fields must be preserved.
    assert_eq!(inner["tag"].as_str().unwrap(), "some-tag");
    assert_eq!(
        inner["subject_id"].as_str().unwrap(),
        subject_id.to_string().as_str()
    );
}

// ── Read path: redaction (DEK deleted) ───────────────────────────────────────

/// Persist a multi-secret event, delete the subject's DEK, then read back and
/// verify that String secret fields are replaced with `"[redacted]"` while
/// plaintext fields are preserved.
#[tokio::test]
async fn multi_secret_redacts_string_fields_when_key_deleted() {
    let (repo, key_store) = make_repo_with_key_store();
    let aggregate_id = "ms-redact";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(&[multi_secret_event(aggregate_id, 1, subject_id)], None)
        .await
        .unwrap();

    // Shred: delete the DEK so decryption is impossible.
    key_store.delete_key(&subject_id).await.unwrap();

    let events = repo
        .get_events::<TestAggregate>(aggregate_id)
        .await
        .unwrap();

    assert_eq!(events.len(), 1);
    let inner = &events[0].payload["MultiSecret"];

    // Secret String fields must be replaced with the "[redacted]" sentinel.
    assert_eq!(
        inner["name"].as_str().unwrap(),
        "[redacted]",
        "name must be redacted after key deletion"
    );
    assert_eq!(
        inner["email"].as_str().unwrap(),
        "[redacted]",
        "email must be redacted after key deletion"
    );

    // Non-PII fields must still be readable.
    assert_eq!(inner["tag"].as_str().unwrap(), "some-tag");
    assert_eq!(
        inner["subject_id"].as_str().unwrap(),
        subject_id.to_string().as_str()
    );
}

/// Persist a single-secret event whose secret field is a `serde_json::Value`,
/// delete the DEK, and verify the field is replaced with an empty JSON object.
#[tokio::test]
async fn single_secret_redacts_value_field_with_empty_object_when_key_deleted() {
    let (repo, key_store) = make_repo_with_key_store();
    let aggregate_id = "ss-redact";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(&[single_secret_event(aggregate_id, 1, subject_id)], None)
        .await
        .unwrap();

    // Shred: delete the DEK.
    key_store.delete_key(&subject_id).await.unwrap();

    let events = repo
        .get_events::<TestAggregate>(aggregate_id)
        .await
        .unwrap();

    assert_eq!(events.len(), 1);
    let inner = &events[0].payload["SingleSecret"];

    // The Value secret field must be replaced with an empty JSON object.
    let data = inner["data"]
        .as_object()
        .expect("data must be a JSON object after redaction");
    assert!(
        data.is_empty(),
        "data must be an empty object `{{}}` after key deletion, got: {:?}",
        inner["data"]
    );

    // Non-PII fields must still be readable.
    assert_eq!(inner["tag"].as_str().unwrap(), "some-tag");
    assert_eq!(
        inner["subject_id"].as_str().unwrap(),
        subject_id.to_string().as_str()
    );
}

// ── Read path: chrono NaiveDate redaction ────────────────────────────────────

/// Persist an event whose secret field is `NaiveDate`, delete the DEK,
/// then read back and verify the field has been replaced with the default
/// sentinel `"0000-01-01"`.
#[cfg(feature = "chrono")]
#[tokio::test]
async fn naive_date_redacts_to_default_sentinel_when_key_deleted() {
    let (repo, key_store) = make_repo_with_key_store();
    let aggregate_id = "nd-redact-default";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(&[dated_secret_event(aggregate_id, 1, subject_id)], None)
        .await
        .unwrap();

    // Shred: delete the DEK so decryption is impossible.
    key_store.delete_key(&subject_id).await.unwrap();

    let events = repo
        .get_events::<TestAggregate>(aggregate_id)
        .await
        .unwrap();

    assert_eq!(events.len(), 1);
    let inner = &events[0].payload["DatedSecret"];

    assert_eq!(
        inner["dob"].as_str().unwrap(),
        "0000-01-01",
        "dob must be the default chrono sentinel after key deletion"
    );

    // Non-PII fields must still be readable.
    assert_eq!(inner["tag"].as_str().unwrap(), "some-tag");
    assert_eq!(
        inner["subject_id"].as_str().unwrap(),
        subject_id.to_string().as_str()
    );
}

/// Persist an event whose secret field is `NaiveDate` with an explicit
/// `redact = "1900-01-01"` override, delete the DEK, then read back and
/// verify the field equals the override value, not the default sentinel.
#[cfg(feature = "chrono")]
#[tokio::test]
async fn naive_date_override_redacts_to_custom_sentinel_when_key_deleted() {
    let (repo, key_store) = make_repo_with_key_store();
    let aggregate_id = "nd-redact-override";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(
        &[dated_secret_override_event(aggregate_id, 1, subject_id)],
        None,
    )
    .await
    .unwrap();

    key_store.delete_key(&subject_id).await.unwrap();

    let events = repo
        .get_events::<TestAggregate>(aggregate_id)
        .await
        .unwrap();

    assert_eq!(events.len(), 1);
    let inner = &events[0].payload["DatedSecretOverride"];

    assert_eq!(
        inner["dob"].as_str().unwrap(),
        "1900-01-01",
        "dob must be the override sentinel after key deletion, not the default"
    );

    assert_eq!(inner["tag"].as_str().unwrap(), "some-tag");
    assert_eq!(
        inner["subject_id"].as_str().unwrap(),
        subject_id.to_string().as_str()
    );
}

// ── Non-string plaintext fields ──────────────────────────────────────────────

/// Persist an event whose plaintext fields include an `i32` and an
/// `Option<String>`, then inspect the raw stored payload. The numeric and
/// optional fields must retain their original JSON types — not be coerced
/// to the empty string.
#[tokio::test]
async fn typed_plaintext_preserves_numeric_and_optional_fields_on_persist() {
    let repo = make_repo();
    let aggregate_id = "tp-persist";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(
        &[typed_plaintext_event(
            aggregate_id,
            1,
            subject_id,
            7,
            Some("hi"),
        )],
        None,
    )
    .await
    .unwrap();

    let raw = repo.inner().all_events();
    let inner = &raw[0].payload["TypedPlaintext"];

    assert_eq!(
        inner["count"].as_i64(),
        Some(7),
        "numeric plaintext field must remain a JSON number after persist, got {:?}",
        inner["count"]
    );
    assert_eq!(
        inner["label"].as_str(),
        Some("hi"),
        "Some(_) plaintext field must remain a JSON string after persist, got {:?}",
        inner["label"]
    );
}

/// `Option<String>::None` plaintext fields must remain JSON `null` in the
/// persisted payload, not be coerced to an empty string.
#[tokio::test]
async fn typed_plaintext_preserves_null_optional_field_on_persist() {
    let repo = make_repo();
    let aggregate_id = "tp-persist-null";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(
        &[typed_plaintext_event(aggregate_id, 1, subject_id, 0, None)],
        None,
    )
    .await
    .unwrap();

    let raw = repo.inner().all_events();
    let inner = &raw[0].payload["TypedPlaintext"];

    assert!(
        inner["label"].is_null(),
        "None plaintext field must remain JSON null after persist, got {:?}",
        inner["label"]
    );
    assert_eq!(
        inner["count"].as_i64(),
        Some(0),
        "the integer 0 must remain a JSON number after persist, got {:?}",
        inner["count"]
    );
}

/// Full classify → persist → reconstruct round-trip for non-string plaintext
/// fields. The reconstructed payload must preserve the original JSON types
/// for both `i32` and `Option<String>` plaintext fields.
#[tokio::test]
async fn typed_plaintext_round_trips_non_string_fields() {
    let repo = make_repo();
    let aggregate_id = "tp-roundtrip";
    let subject_id = Uuid::new_v4();

    repo.persist::<TestAggregate>(
        &[typed_plaintext_event(
            aggregate_id,
            1,
            subject_id,
            -42,
            Some("kept"),
        )],
        None,
    )
    .await
    .unwrap();

    let events = repo
        .get_events::<TestAggregate>(aggregate_id)
        .await
        .unwrap();

    assert_eq!(events.len(), 1);
    let inner = &events[0].payload["TypedPlaintext"];

    assert_eq!(inner["count"].as_i64(), Some(-42));
    assert_eq!(inner["label"].as_str(), Some("kept"));
    assert_eq!(inner["secret_value"].as_str().unwrap(), "the-secret");
    assert_eq!(
        inner["subject_id"].as_str().unwrap(),
        subject_id.to_string().as_str()
    );
}
